version: '3'
services:
  api:
    build: .
    env_file:
    - ./.env.docker
    ports:
    - "3030:3030"
    links:
    - mongo
    command: ["bin/atomicagent", "api"]
  worker:
    build: .
    env_file:
    - ./.env.docker
    ports:
    - "3031:3031"
    links:
    - mongo
    command: ["bin/atomicagent", "worker"]
  mongo:
    image: mongo
