name: 'deploy-to-personal'

on:
  push:
    branches:
      # - dev
      - dockerized
    paths:
      - 'env/personal/**'
      - 'src/**'
      - '.github/workflows/docker-push-to-personal.yml'

env:
  ENV_ALIAS: 'personal'
  AWS_REGION: 'us-east-2'
  AWS_ECR_REGISTRY: '465533514173.dkr.ecr.us-east-2.amazonaws.com'
  DOCKER_IMAGE_NAME: 'atomicagent-personal'
  DOCKERFILE_PATH: 'api.dockerfile'

jobs:
  docker-deploy:
    name: 'Building and Deploying Image'
    runs-on: ubuntu-latest
    environment: personal

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ECR
        id: login-ecr
        run: |
          export AWS_DEFAULT_REGION=${{ env.AWS_REGION }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

      # # Load AWS credentials (this is the ecs-service service account)
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-skip-session-tagging: true
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     aws-region: ${{ env.AWS_REGION }}
      #
      # # Login to ECR
      # - name: Login to AWS ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # Build, tag, and push Docker image to ECR
      - name: Build/tag/push image to ECR
        id: build-image
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REPOSITORY: ${{ env.DOCKER_IMAGE_NAME }}
          # IMAGE_TAG: ${{ github.sha }}
          DOCKER_IMAGE_TAG: 'latest'
        run: |
          echo "Working Dir !!!"
          pwd
          export CONFIG_PATH=env/$ENV_ALIAS/config.$ENV_ALIAS.toml
          echo $CONFIG_PATH
          source ./bin/docker-deploy.sh "$ENV_ALIAS" "$AWS_ECR_REGISTRY" "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_TAG" "$DOCKERFILE_PATH"

      # Trigger update to ECS cluster
      - name: Update ECS
        id: update-ecs
        run: |
          aws ecs update-service --cluster "${DOCKER_IMAGE_NAME}" --service "${DOCKER_IMAGE_NAME}" --force-new-deployment
