name: Publish & reload

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - run: npm publish --access public --tag next
        if: contains(github.ref, '-next.')
      - run: npm publish --access public
        if: contains(github.ref, '-next.') != true

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.')
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.') != true
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload
