name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/cache@v1
        env:
          node-version: 8
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - run: cp sample.config.toml test.config.toml
      - run: npm run env:docker
      - run: sleep 60
      - run: npm ci
      - run: npm test
