# This actions runs against every Tag to Prod (or) next tag(Ex:v0.4.6-next.3) to dev
name: Test, publish & deploy

on:
  push:
    tags:
      - v*

jobs:
  test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v1
        env:
          node-version: 14
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}-${{ hashFiles('**/package-lock.json') }}

      # Git secrets set for Dev tag
      - name: Set secrets for DEV
        if: contains(github.ref, '-next.')
        env:
          VUE_APP_AMPLITUDE_API_KEY: ${{ secrets.VUE_APP_AMPLITUDE_API_KEY_DEV }}
        run: |
          echo VUE_APP_AMPLITUDE_API_KEY =${{ secrets.VUE_APP_AMPLITUDE_API_KEY_DEV }} >> .env

      # Git secrets set for Prod tag
      - name: Set secrets for PROD
        if: contains(github.ref, '-next.') != true
        env:
          VUE_APP_AMPLITUDE_API_KEY: ${{ secrets.VUE_APP_AMPLITUDE_API_KEY }}
        run: |
          echo VUE_APP_AMPLITUDE_API_KEY =${{ secrets.VUE_APP_AMPLITUDE_API_KEY }} >> .env

      # Run Docker start, node starts
      - name: Build project & docker start
        run: |
          cp sample.config.toml test.config.toml
          chmod -R 777 test/docker/config
          npm run docker:start
          sleep 30

      # Run npm scripts
      - name: npm ci & lint & test
        run: |
          npm ci
          npm run lint
          npm test
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - run: npm publish --access public --tag next
        if: contains(github.ref, '-next.')
      - run: npm publish --access public
        if: contains(github.ref, '-next.') != true

  deploy:
    needs: test_publish
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.')
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload_next
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.') != true
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload
